Add new files1

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,3 +1,42 @@
+# name: Cypress Tests
+
+# on: push
+
+# jobs:
+#   test:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Get code
+#         uses: actions/checkout@v3
+
+#       - name: Install NodeJS
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: 18
+
+#       - name: Install dependencies
+#         run: npm install
+
+#       - name: Clean up old reports
+#         run: rm -rf cypress/reports || true
+
+#       - name: Run Cypress tests
+#         run: npx cypress run --browser chrome
+
+#       - name: Merge Mochawesome reports
+#         run: npm run merge-reports
+
+#       - name: Generate HTML report
+#         run: npx marge cypress/reports/merged-report.json -o cypress/reports/report.html
+
+#       - name: Upload report as artifact
+#         uses: actions/upload-artifact@v3
+#         with:
+#           name: cypress-report
+#           path: cypress/reports/report.html
+#       - name: Cypress tests
+#         uses: cypress-io/github-action@v6
 name: Cypress Tests
 
 on: push
@@ -22,7 +61,13 @@ jobs:
         run: rm -rf cypress/reports || true
 
       - name: Run Cypress tests
-        run: npx cypress run --browser chrome
+        uses: cypress-io/github-action@v6
+        with:
+          start: npm start
+          wait-on: "http://localhost:3000"
+          wait-on-timeout: 60 # seconds
+        env:
+          CYPRESS_baseUrl: http://localhost:3000
 
       - name: Merge Mochawesome reports
         run: npm run merge-reports
@@ -35,5 +80,3 @@ jobs:
         with:
           name: cypress-report
           path: cypress/reports/report.html
-      - name: Cypress tests
-        uses: cypress-io/github-action@v6
